// File: postgres.go

package grnoti

import (
	"context"
	_ "embed"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/gourdian25/grnoti/internal/postgresdb"
)

// pgTimestamptz and pgTime convert between time.Time and pgtype.Timestamptz
// — shared by every Postgres store's row<->domain mapping.
func pgTimestamptz(t time.Time) pgtype.Timestamptz {
	return pgtype.Timestamptz{Time: t, Valid: !t.IsZero()}
}

func pgTime(t pgtype.Timestamptz) time.Time {
	if !t.Valid {
		return time.Time{}
	}
	return t.Time.UTC()
}

// postgresSchemaSQL is internal/postgresdb/schema.sql, embedded so every
// Postgres-backed store (TokenStore, PreferencesStore, ExperimentStore,
// DLQHandler) can apply it on connect without a separate migration tool —
// grnoti has one linear schema, and CREATE TABLE IF NOT EXISTS is
// sufficient. The query code itself is generated by sqlc from the same
// directory (see internal/postgresdb) into its own internal package —
// standard Go practice for isolating generated code from hand-written
// code, and distinct from the subpackage-per-backend pattern grnoti
// deliberately avoids (see docs/plan/grnoti-plan.md §4): internal/
// packages aren't importable outside this module at all, so this isn't a
// public API surface the way grcache/redis or grcache/postgres are.
//
//go:embed internal/postgresdb/schema.sql
var postgresSchemaSQL string

// PostgresConfig is the common connection configuration shared by every
// Postgres-backed store.
type PostgresConfig struct {
	// DSN is a standard libpq/pgx connection string. Required.
	DSN string
	// MaxConns caps the pgxpool connection pool size. 0 means use pgxpool's
	// own default.
	MaxConns int32
	// MinConns keeps at least this many connections open. 0 means use
	// pgxpool's own default.
	MinConns int32
	// MaxConnLifetime bounds how long a pooled connection may be reused
	// before being recycled. 0 means pgxpool's own default (unlimited).
	MaxConnLifetime time.Duration
	// Logger receives optional diagnostic messages. A nil Logger disables
	// logging.
	Logger Logger
}

// connectPostgres opens a pgxpool.Pool per cfg, validates connectivity via
// Ping, and applies the embedded schema before returning — shared by every
// Postgres store's own constructor.
func connectPostgres(ctx context.Context, cfg PostgresConfig, component string) (*pgxpool.Pool, *postgresdb.Queries, error) {
	if cfg.DSN == "" {
		return nil, nil, fmt.Errorf("grnoti/postgres: DSN is required for %s", component)
	}

	poolCfg, err := pgxpool.ParseConfig(cfg.DSN)
	if err != nil {
		return nil, nil, fmt.Errorf("grnoti/postgres: parse DSN: %w", err)
	}
	if cfg.MaxConns > 0 {
		poolCfg.MaxConns = cfg.MaxConns
	}
	if cfg.MinConns > 0 {
		poolCfg.MinConns = cfg.MinConns
	}
	if cfg.MaxConnLifetime > 0 {
		poolCfg.MaxConnLifetime = cfg.MaxConnLifetime
	}

	connectCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	pool, err := pgxpool.NewWithConfig(connectCtx, poolCfg)
	if err != nil {
		return nil, nil, fmt.Errorf("grnoti/postgres: connect: %w", errors.Join(err, ErrBackendUnavailable))
	}
	if err := pool.Ping(connectCtx); err != nil {
		pool.Close()
		return nil, nil, fmt.Errorf("grnoti/postgres: ping: %w", errors.Join(err, ErrBackendUnavailable))
	}
	if _, err := pool.Exec(connectCtx, postgresSchemaSQL); err != nil {
		pool.Close()
		return nil, nil, fmt.Errorf("grnoti/postgres: apply schema: %w", err)
	}

	return pool, postgresdb.New(pool), nil
}
