// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package postgresdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPreferences = `-- name: GetPreferences :one

SELECT user_id, global_enabled, quiet_hours_enabled, quiet_hours_start, quiet_hours_end, timezone, locale, event_type_settings, created_at, updated_at FROM grnoti_preferences WHERE user_id = $1
`

// File: internal/postgresdb/queries/preferences.sql
func (q *Queries) GetPreferences(ctx context.Context, userID string) (GrnotiPreference, error) {
	row := q.db.QueryRow(ctx, getPreferences, userID)
	var i GrnotiPreference
	err := row.Scan(
		&i.UserID,
		&i.GlobalEnabled,
		&i.QuietHoursEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
		&i.Timezone,
		&i.Locale,
		&i.EventTypeSettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPreferences = `-- name: UpsertPreferences :exec
INSERT INTO grnoti_preferences (user_id, global_enabled, quiet_hours_enabled, quiet_hours_start, quiet_hours_end, timezone, locale, event_type_settings, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
ON CONFLICT (user_id) DO UPDATE SET
    global_enabled = EXCLUDED.global_enabled,
    quiet_hours_enabled = EXCLUDED.quiet_hours_enabled,
    quiet_hours_start = EXCLUDED.quiet_hours_start,
    quiet_hours_end = EXCLUDED.quiet_hours_end,
    timezone = EXCLUDED.timezone,
    locale = EXCLUDED.locale,
    event_type_settings = EXCLUDED.event_type_settings,
    updated_at = EXCLUDED.updated_at
`

type UpsertPreferencesParams struct {
	UserID            string             `db:"user_id" json:"user_id"`
	GlobalEnabled     bool               `db:"global_enabled" json:"global_enabled"`
	QuietHoursEnabled bool               `db:"quiet_hours_enabled" json:"quiet_hours_enabled"`
	QuietHoursStart   string             `db:"quiet_hours_start" json:"quiet_hours_start"`
	QuietHoursEnd     string             `db:"quiet_hours_end" json:"quiet_hours_end"`
	Timezone          string             `db:"timezone" json:"timezone"`
	Locale            string             `db:"locale" json:"locale"`
	EventTypeSettings []byte             `db:"event_type_settings" json:"event_type_settings"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) UpsertPreferences(ctx context.Context, arg UpsertPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertPreferences,
		arg.UserID,
		arg.GlobalEnabled,
		arg.QuietHoursEnabled,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
		arg.Timezone,
		arg.Locale,
		arg.EventTypeSettings,
		arg.CreatedAt,
	)
	return err
}
